---
id: Refactor
name: Refactor
full: PHP code refactoring library
description: >
  An extendable set of classes and a command line tool to refactor files or
  complete directories.
list: dev
type: library
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
version:
  release: 1.0.0alpha1
  api: 1.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: BSD
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^5.5
    pear:
      pear.horde.org/Horde_Cli: ^2.1
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Text_Diff: ^2.2
      pear.horde.org/Horde_Translation: ^2.2.2
